
Promise.resolve(42).then(() => {
    throw 'uncaught error inside promise';
})


Promise.ra  ce